### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by StageGuard** [StageGuard/Aruku#1]
- [x] separate `ArukuMiraiService` as backend module, export common module for external backend.
- [x] move audio cache to application instead of backend service.
- [x] create common service to handle external service backend.
- [x] external backend loader in `ArukuService`.
- [x] backend connection bug on `MainActivity` lifecycle changes.
- [ ] recover login state when restarting backend service while `ArukuService` is present.
- [ ] check `ArukuService` connection when killed `ArukuService` manually in `MainActivity`.
- [ ] rewrite `LoginSolver`
- [ ] external backend selector in application.
- [ ] bottom bar for chat page.
- [ ] rewrite login page view model
- [ ] ......
